### PR TITLE
Improvements to Key Cacher interface

### LINKED ISSUE #34: Allowing different cacher
Currently, the JWK Client will only save all the downloaded key and keep expanding the cache as there are more keys. This may lead to security flaw.
It would be nice to support a cache with maximum age of each key entry and size of the cache.
It would also be nice to support cacher interface so everyone can implement their own cacher to cache keys according to their needs.

### PR DESCRIPTION
**Pull request by Tuanhao**
This PR:
- [x] includes various improvements to Key Cacher interface.
- [x] updates the README on Key Cacher interface

This resolves #34

### CODE REVIEW

**Comment by Tuanhao** [comment]
@ttjiaa

**Comment by ttjiaa** [comment]
@yageek PTAL

**Comment by yageek** [comment]
Great Work 👍 I take a look ASAP.

**Comment by ttjiaa** [comment]
Thanks @yageek!

**Pull request merged**
